# Numpy

In [1]:

import numpy as np

# Initializing numpy array
x =np.zeros((3,5),dtype=int)

np.ones_like(x)

np.full_like(x,3)

np.identity(3)

np.diag([1,2,3,4])

np.arange(0,11,2)

np.linspace(0,25,10)

np.reshape(x,[3,3])

np.linspace(0,50,20).reshape([5,4])

np.random.random([4,3])

np.random.randint(2,8,[3,3])

np.random.normal(0,10,[50,50])  #0 mean, 10 STD




hi


In [ ]:
import numpy as np

x = np.array([
    [0.76021683, 0.23538932, 0.82001752],
    [0.71836726, 0.43139469, 0.50619972],
    [0.24757373, 0.02761646, 0.77621469],
    [0.78063444, 0.51646522, 0.88814931],
    [0.41655595, 0.2936441, 0.7060387]])

x[1, 1] == x[1][1]

# removes 0 and 2 column from array
np.delete(x, [0, 2], axis=1)
# removes 0 and 2 row from array
np.delete(x, [0, 2], axis=0)
# removes even index values from array
np.delete(x, [*range(0, x.size, 2)])

# append values
np.append(x, [4, 5])
np.append(x, [[4, 4, 4]], axis=0)
np.append(x, [[4], [4], [4], [4], [4]], axis=1)

# vertical stack
np.vstack((x, [[4, 4, 4]]))
# horizontal stack
np.hstack((x, [[4], [4], [4], [4], [4]]))

# insert at position these values
np.insert(x, 9, [4, 5, 6, 7])
# insert array at given row
np.insert(x, 2, [4, 5, 6, ], axis=0)
# insert array at given column
np.insert(x, 2, [4, 5, 6, 7, 8], axis=1)

# slicing
x[1:4, 1]
# If done this way, changes in y will chande vlues in x too
y = x[0:3]
y[2, 1] = 99

# using of copy makes y independant of x
y = x[0:3].copy()
y[2, 1] = 99

# same concept can be observed in nomal lists
import copy

xx = list([list(i) for i in x])
yy = xx[:3]
yy = copy.deepcopy(xx)
yy[0][0] = 5555
yy
xx

# extract diagonal
np.diag(x)
# offest by k
np.diag(x, k=1)

# get unique
np.unique([4, 5, 6, 6])

# specifies we need 1 column only, pack all stuff in one
x.reshape(-1, 1)
# specifies we need row column only, pack all stuff in one
x.reshape(1, -1)

# masking, conditioning
x[(x > 3) | (x < 0.3)] = 33
x[[False, False, False, True, False]]

# set functions
np.union1d(x, x * 2)
np.intersect1d(x, x)
np.setdiff1d(x, x)

np.sort(x, axis=1)
np.sort(x, axis=0)
x.sort()

# broadcasting
x = np.ones(9, dtype=int).reshape(3, 3)
y = np.ones(3, dtype=int).reshape(1, 3) + 1
np.add(x, y)
x + y
# scalar
np.add(x, 1)
x + 1

x = np.insert(x, 1, [[3], [3]], axis=1)
# this thing works exactly for sum, std, min, max etc
np.mean(x)
np.mean(x, axis=0)
np.mean(x, axis=1)

# functions called with np.func(x) dont change the values of x while
# funtions called with x.func will probably change x


In [ ]:
#sub arrays also reversed
x2[::-1, ::-1]


# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

In [ ]:
x = np.ones((3,3)) >>> x
array([[ 1., 1., 1.], [ 1., 1., 1.], [ 1., 1., 1.]])
>>> x[:,[0,1,2,2]] # notice duplicated last dimension array([[ 1., 1., 1., 1.], [ 1., 1., 1., 1.], [ 1., 1., 1., 1.]])
>>> y=x[:,[0,1,2,2]] # same as above, but do assign it to y
However, ifwe start over and construct y by slicing (whichmakes it a view) as shown below, then the change we made does affect y because a view is just a window into the same memory.
>>> x = np.ones((3,3)) >>> y = x[:2,:2] # view of upper left piece >>> x[0,0] = 999 # change value >>> x
array([[ 999., 1., 1.], # see the change? [ 1., 1., 1.], [ 1., 1., 1.]])
>>> y
array([[ 999., 1.], # changed y also! [ 1., 1.]])
Note that if you want to explicitly force a copy without any indexing tricks, you can do y=x.copy().


In [ ]:
 A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling reduce on the add ufunc returns the sum of all elements in the array:

26
x = np.arange(1, 6)
np.add.reduce(x)
26
15
Similarly, calling reduce on the multiply ufunc results in the product of all array elements:

27
np.multiply.reduce(x)
27
120
If we'd like to store all the intermediate results of the computation, we can instead use accumulate:

28
np.add.accumulate(x)
28
array([ 1,  3,  6, 10, 15])
29
np.multiply.accumulate(x)