# Numpy

In [2]:
import numpy as np

### Initialization


In [ ]:
# from zeroes
x =np.zeros((3,5),dtype=int)



In [26]:
np.ones((3,2))

# uses the dimensions or shape of x
np.ones_like(x)

<IPython.core.display.Javascript object>

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# from a number n
n=4
np.full_like(x,n)

<IPython.core.display.Javascript object>

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [28]:

np.identity(3)

#np.eye(4) # probably same

<IPython.core.display.Javascript object>

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.diag([1,2,3,4])


<IPython.core.display.Javascript object>

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.arange(0,11,2)



In [ ]:
np.linspace(0,25,10)



In [33]:
# from random numbers within 0-1 range
np.random.random([4,3])*100


<IPython.core.display.Javascript object>

array([[ 7.81903638, 42.5701113 , 32.87613083],
       [41.67184055, 37.86754855, 52.85878632],
       [25.25078247, 54.92686213, 10.85371187],
       [88.85632088, 21.24364029, 78.9336317 ]])

In [34]:
np.random.randint(2,8,[3,3])


<IPython.core.display.Javascript object>

array([[4, 4, 2],
       [6, 2, 3],
       [5, 6, 7]])

In [37]:
# normal distribution
np.random.normal(0,1,[5,5])  #0 mean, 1 STD


<IPython.core.display.Javascript object>

array([[-0.65056013,  0.72899474, -0.94529462, -0.15331018,  0.55283655],
       [ 0.97556946,  0.08279676, -0.33191931, -0.31309976, -0.61464341],
       [ 1.10840561,  0.2576429 , -0.09350273,  0.33207657,  0.95563647],
       [-0.4295953 , -0.05812639, -0.97658097,  0.28409976, -0.81814141],
       [-1.3319473 , -1.94666466,  0.23441067,  0.12127661,  0.00417129]])

In [36]:
# uniform distribution bw 0-1
np.random.uniform(0,1,[5,5])



<IPython.core.display.Javascript object>

array([[0.81088202, 0.19712839, 0.82188898, 0.85293068, 0.44135496],
       [0.32710624, 0.19725999, 0.55277309, 0.05650581, 0.67467285],
       [0.92681255, 0.4971018 , 0.09252057, 0.02451113, 0.43132075],
       [0.46998989, 0.53859556, 0.23998296, 0.05615469, 0.46949435],
       [0.9794441 , 0.45036613, 0.61366528, 0.54614692, 0.76572088]])

In [292]:
x.ndim

2

In [293]:
x.size

9

In [294]:
x.shape

(3, 3)

## Slicing

In [ ]:

# slicing
x[1:4, 1]

# using of copy makes y independant of x
y = x[0:3].copy()
y[2, 1] = 99

In [ ]:
# View and Copy
x = np.ones((3,3))
y = x[:2,:2]
y[0][0] = 4
y
x

In [ ]:
# reverse slicing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[1,1:4:1])
print(a[1,3:0:-1])



In [ ]:
# this type of indexing works too
x[:,[0,1,2,2,1]]
x[[0,1,2,2,1],:]



## Broadcasting

In [125]:
# Broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x*v)


# thats what broadcasting does
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"



<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


<IPython.core.display.Javascript object>

In [146]:

# Another example of broadcasting
v = np.array([[1,2,3]]).T  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

print(v* w)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[ 4  5]
 [ 8 10]
 [12 15]]


## Manipulation



In [ ]:
np.linspace(0,50,20).reshape([5,4])



In [ ]:
# reshape with unknown dimension
x.reshape([10,-1])



In [ ]:
# rotate both axes
np.flip(x)

In [ ]:
# saving and loading
np.savetxt('new_file.csv', x)
np.loadtxt('new_file.csv', x)

In [176]:

# removes 0 and 2 column from array
np.delete(x, [0, 2], axis=1)
# # removes 0 and 2 row from array
np.delete(x, [0, 2], axis=0)
# # removes even index values from array
np.delete(x, [*range(0, x.size, 2)])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1, 1, 1, 1])

In [197]:

# append values
np.append(x, [4, 5])
np.append(x, [[4, 4, 4]], axis=0)
np.append(x, [[4], [4], [4]], axis=1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[1, 1, 1, 4],
       [1, 1, 1, 4],
       [1, 1, 1, 4]])

In [215]:
# vertical stack
np.vstack((x, [4, 4, 4]))
# horizontal stack
np.hstack((x, [[4], [4], [4]]))
# concatenate along the second axis (zero-indexed)
np.concatenate([x, x], axis=1)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [241]:
# spliting insverse to stacking
np.hsplit(x,[1,2])
np.vsplit(x,[1,2])


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[array([[1, 1, 1]]), array([[1, 1, 1]]), array([[1, 1, 1]])]

In [260]:
# insert at position these values
np.insert(x, 3, [4, 5, 6, 7])
# insert array at given row
np.insert(x, 2, [4, 5, 6, ], axis=0)
# insert array at given column
np.insert(x, 2, [4, 5, 6, ], axis=1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[1, 1, 4, 1],
       [1, 1, 5, 1],
       [1, 1, 6, 1]])

In [261]:

# extract diagonal
np.diag(x)

# offest by k
np.diag(x, k=1)

<IPython.core.display.Javascript object>

array([1, 1, 1])

In [254]:
# convert to 1D
x.flatten() # changes arent propagated to parent array
x.ravel()   # changes will change parent array
# x.reshape(1,-1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [263]:

# get unique
np.unique([4, 5, 6, 6])


<IPython.core.display.Javascript object>

array([4, 5, 6])

In [ ]:


# specifies we need 1 column only, pack all stuff in one
x.reshape(-1, 1)
# specifies we need row column only, pack all stuff in one
x.reshape(1, -1)


In [ ]:
# masking, conditioning
x[(x > 3) | (x < 0.3)] = 33
x[[False, False, False, True, False]]

In [ ]:
# set functions
np.union1d(x, x * 2)
np.intersect1d(x, x)
np.setdiff1d(x, x)


In [275]:

np.sort(x, axis=1)
np.sort(x, axis=0)
x.sort()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# scalar
np.add(x, 1)
# this thing works exactly for sum, std, min, max etc
np.mean(x)
np.mean(x, axis=0)
np.mean(x, axis=1)



In [315]:
# checking mask along axis
x.all(axis = 1)

array([ True,  True,  True])

In [291]:
np.add.accumulate(x)


<IPython.core.display.Javascript object>

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)

In [ ]:
# A reduce repeatedly applies a given operation to the elements of an
# array until only a single result remains.
# For example, calling reduce on the add ufunc returns the sum of all
# elements in the array:

np.add.reduce(x)
# np.sum(x, axis =0) # probably this is the same thing

# Similarly, calling reduce on the multiply ufunc results in the
# product of all array elements:

np.multiply.reduce(x)
# If we'd like to store all the intermediate results of the computation,
# we can instead use accumulate:

# works like cumulative func like cumsum()
np.add.accumulate(x)
np.multiply.accumulate(x)


In [33]:
import numpy as np
x= np.array([[4,5],[6,6]])
x
np.matmul(x,x)

array([[46, 50],
       [60, 66]])

In [37]:
# matrix vector product
# x@[1,0,1]
# x.dot([1,0,1])
# np.matmul(x,[1,0,1])


# Vector/Matrix operations
# Basic matrix and vector operations which will be useful for assignments

# vector x vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1)
print('Array2 \n', array2)

print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', np.matmul(array1, array2))
print("Matmul of the two arrays can also be derived by using array1@array2 \n", array1@array2)
print('Dimensions of resulting product: \n', np.matmul(array1, array2).shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, "\n")
print('Array4 \n', array4, "\n")


print('Matmul of the a vector and a matrix can be derived by using np.matmul(array3, array4) \n', np.matmul(array3, array4))
print('Matmul of the a vector and a matrix can also be derived by using array3@array4 \n', array3@array4)
print('Dimensions of resulting product: \n', np.matmul(array3, array4).shape)

## Matrix x Matrix

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

product = matrix1.dot(matrix2)

print('Using DOT: product= \n\n', product, '\n\nproduct.shape =', product.shape)
print("array3@array4 is an equivalent way of dot product \n", matrix1@matrix2, '\n\nproduct.shape =', (matrix1@matrix2).shape)

# Using einsum
product = np.einsum('ik, kj', matrix1, matrix2)
print('\n\nUsing einsum: product= \n\n', product, '\n\nproduct.shape =', product.shape)

# Note, the above einsum notation is equivalent to the following
product = np.einsum('ik, kj -> ij', matrix1, matrix2)



Array1 
 [-1.47578256 -0.39381149  0.75440362]
Array2 
 [-0.51835824 -1.69997651  1.21352318]
Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 2.3499405986242663
Matmul of the two arrays can also be derived by using array1@array2 
 2.3499405986242663
Dimensions of resulting product: 
 ()
Array3 
 [[ 0.13948958  0.98918515  1.46256525 -0.87853991]
 [ 1.04481442 -1.66369832 -0.13654859 -0.83719198]
 [ 0.65334143  1.61311485 -2.13577499  0.19057976]] 

Array4 
 [ 0.30451297 -1.52441859  0.6891041  -2.27993411] 

Matmul of the a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [ 1.54541698  4.66897854 -4.16639193]
Matmul of the a vector and a matrix can also be derived by using array3@array4 
 [ 1.54541698  4.66897854 -4.16639193]
Dimensions of resulting product: 
 (3,)
Using DOT: product= 

 [[ 7  9]
 [15 16]] 

product.shape = (2, 2)
array3@array4 is an equivalent way of dot product 
 [[ 7  9]
 [15 16]] 

product.shape = (2, 2)


Using e

In [ ]:
# useful functions
"""
Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity,
linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack,
ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take,
transpose, vsplit, vstack

Questions
all, any, nonzero, where

Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask,
real, sum

Basic Statistics
cov, mean, std, var

Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot"""